import assert from 'node:assert/strict';
import test from 'node:test';
import { translateSegments, PROFILE_VERSION } from './engine.js';
import { canonicalLanguage } from './language.js';

const QWEN = 'qwen3//models/Qwen3-8B-Q4_K_M.gguf';
const QWEN_RESPONSE = '/models/Qwen3-8B-Q4_K_M.gguf';
const GRANITE = 'granite//models/granite-4.2-8b-Q4_K_M.gguf';
const GRANITE_RESPONSE = '/models/granite-4.2-8b-Q4_K_M.gguf';
const CONFIG = { aiCore: { baseUrl: 'http://127.0.0.1:18080', apiKey: 'test-key' }, timeoutMs: 30_000 };
const MEANING_EN = JSON.stringify({ detected_language: 'en', claims: ['same meaning'], constraints: [], conditions: [], entities: [], quantities: [], uncertainties: [] });
type RequestBody = { model: string; messages: Array<{ role: string; content: string }>; temperature: number; chat_template_kwargs: { enable_thinking: boolean } };
function body(init: RequestInit | undefined): RequestBody { return JSON.parse(String(init?.body)) as RequestBody; }
function user(request: RequestBody): string { return request.messages.find((item) => item.role === 'user')?.content ?? ''; }
function system(request: RequestBody): string { return request.messages.find((item) => item.role === 'system')?.content ?? ''; }
function translation(request: RequestBody): boolean { return request.model === QWEN && user(request).includes('BEGIN_BATCH'); }
function response(model: string, content: string): Response { return new Response(JSON.stringify({ model, choices: [{ message: { content } }], usage: { prompt_tokens: 12, completion_tokens: 8 } }), { status: 200, headers: { 'content-type': 'application/json' } }); }
function pass(): string { return JSON.stringify({ equivalent: true, score: 1, target_language_match: true, critical_differences: [] }); }
function req(overrides: Record<string, unknown> = {}): Record<string, unknown> { return { request_id: 'req-1', profile_version: PROFILE_VERSION, target_language: 'ja', segments: [{ id: 's1', text: '# Hello\nKeep 2026-12-31 $125.50 USD v8.4.1 https://example.com `const x = 1`' }, { id: 's2', text: '- World\n- UUID 550e8400-e29b-41d4-a716-446655440000 95%' }], ...overrides }; }

test('canonicalizes valid BCP47 language tags', () => { assert.equal(canonicalLanguage('ZH-cn', 'target_language'), 'zh-CN'); });
test('rejects invalid target language before AI access', async () => { let calls = 0; const old = globalThis.fetch; globalThis.fetch = async () => { calls += 1; throw new Error('no'); }; try { await assert.rejects(() => translateSegments(req({ target_language: 'not_a_language' }), CONFIG), (e: unknown) => (e as { code?: string }).code === 'TARGET_LANGUAGE_INVALID'); assert.equal(calls, 0); } finally { globalThis.fetch = old; } });
test('glossary is fail-closed while not implemented', async () => { let calls = 0; const old = globalThis.fetch; globalThis.fetch = async () => { calls += 1; throw new Error('no'); }; try { await assert.rejects(() => translateSegments(req({ glossary_id: 'legal-v1' }), CONFIG), (e: unknown) => (e as { code?: string }).code === 'TRANSLATION_GLOSSARY_NOT_IMPLEMENTED'); assert.equal(calls, 0); } finally { globalThis.fetch = old; } });
test('batches generic segments, protects critical values, and validates with independent Qwen plus Granite', async () => { const old = globalThis.fetch; const requests: RequestBody[] = []; globalThis.fetch = async (_input, init) => { const request = body(init); requests.push(request); assert.equal(request.temperature, 0); assert.equal(request.chat_template_kwargs.enable_thinking, false); if (translation(request)) { const content = user(request); assert.match(content, /__ASTERIA_SECTION_000000_BEGIN__/); assert.doesNotMatch(content, /2026-12-31|\$125\.50|v8\.4\.1|https:\/\/example\.com|`const x = 1`/); const batch = content.match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; return response(QWEN_RESPONSE, batch.replace('Hello', 'こんにちは').replace('World', '世界')); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); assert.equal(request.model, GRANITE); assert.match(system(request), /untrusted data/); return response(GRANITE_RESPONSE, pass()); }; try { const out = await translateSegments(req(), CONFIG); assert.match(out.segments[0]!.text, /こんにちは.*2026-12-31.*\$125\.50 USD.*v8\.4\.1.*https:\/\/example\.com.*`const x = 1`/s); assert.equal(out.usage.calls, 4); assert.equal(out.language_capability_status, 'NOT_VERIFIED'); assert.equal(requests.filter(translation).length, 1); } finally { globalThis.fetch = old; } });
test('semantic mismatch retries from original and passes only after second verdict', async () => { const old = globalThis.fetch; let translations = 0; let verdicts = 0; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { translations += 1; const content = user(request); const batch = content.match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; if (translations === 1) return response(QWEN_RESPONSE, batch.replace('Hello', 'Publish')); assert.match(content, /STRATEGY=semantic_retry/); assert.match(content, /negation removed/); return response(QWEN_RESPONSE, batch.replace('Hello', 'こんにちは')); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); verdicts += 1; return response(GRANITE_RESPONSE, verdicts === 1 ? JSON.stringify({ equivalent: false, score: 0.6, target_language_match: true, critical_differences: ['negation removed'] }) : pass()); }; try { const out = await translateSegments(req(), CONFIG); assert.equal(translations, 2); assert.equal(verdicts, 2); assert.equal(out.usage.calls, 7); assert.equal(out.usage.semantic_retries, 1); } finally { globalThis.fetch = old; } });
test('target-language mismatch causes one semantic retry', async () => { const old = globalThis.fetch; let translations = 0; let verdicts = 0; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { translations += 1; const content = user(request); const batch = content.match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; if (translations === 2) assert.match(content, /requested target language sw/); return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); verdicts += 1; return response(GRANITE_RESPONSE, verdicts === 1 ? JSON.stringify({ equivalent: true, score: 1, target_language_match: false, critical_differences: [] }) : pass()); }; try { const out = await translateSegments(req({ target_language: 'sw' }), CONFIG); assert.equal(translations, 2); assert.equal(out.usage.semantic_retries, 1); } finally { globalThis.fetch = old; } });
test('requested source language mismatch fails closed', async () => { const old = globalThis.fetch; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { const batch = user(request).match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, JSON.stringify({ detected_language: 'en', claims: [], constraints: [], conditions: [], entities: [], quantities: [], uncertainties: [] })); return response(GRANITE_RESPONSE, pass()); }; try { await assert.rejects(() => translateSegments(req({ source_language: 'de' }), CONFIG), (e: unknown) => (e as { code?: string }).code === 'SOURCE_LANGUAGE_MISMATCH'); } finally { globalThis.fetch = old; } });
test('structure corruption triggers one whole-batch line fallback', async () => { const old = globalThis.fetch; let translations = 0; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { translations += 1; const content = user(request); const batch = content.match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; if (translations === 1) return response(QWEN_RESPONSE, `${batch}\nBROKEN`); assert.match(content, /STRATEGY=lines/); return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); return response(GRANITE_RESPONSE, pass()); }; try { const out = await translateSegments(req(), CONFIG); assert.equal(translations, 2); assert.equal(out.usage.validation_fallbacks, 1); assert.equal(out.usage.calls, 5); } finally { globalThis.fetch = old; } });
test('second semantic mismatch fails closed', async () => { const old = globalThis.fetch; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { const batch = user(request).match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); return response(GRANITE_RESPONSE, JSON.stringify({ equivalent: false, score: 0.5, target_language_match: true, critical_differences: ['meaning differs'] })); }; try { await assert.rejects(() => translateSegments(req(), CONFIG), (e: unknown) => (e as { code?: string }).code === 'TRANSLATION_SEMANTIC_EQUIVALENCE_FAILED'); } finally { globalThis.fetch = old; } });
test('rejects non-loopback AI Core before network access', async () => { const old = globalThis.fetch; let calls = 0; globalThis.fetch = async () => { calls += 1; throw new Error('no'); }; try { await assert.rejects(() => translateSegments(req(), { aiCore: { baseUrl: 'https://ai.example.com', apiKey: 'x' }, timeoutMs: 1000 }), (e: unknown) => (e as { code?: string }).code === 'TRANSLATION_AI_CORE_LOCAL_ONLY'); assert.equal(calls, 0); } finally { globalThis.fetch = old; } });
test('fails closed when Granite response identity is wrong', async () => { const old = globalThis.fetch; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { const batch = user(request).match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); return response(QWEN_RESPONSE, pass()); }; try { await assert.rejects(() => translateSegments(req(), CONFIG), (e: unknown) => (e as { code?: string }).code === 'TRANSLATION_MODEL_IDENTITY_MISMATCH'); } finally { globalThis.fetch = old; } });
test('empty segment is preserved and never added to model batch', async () => { const old = globalThis.fetch; globalThis.fetch = async (_input, init) => { const request = body(init); if (translation(request)) { const content = user(request); assert.doesNotMatch(content, /empty-id/); const batch = content.match(/BEGIN_BATCH\n([\s\S]*)\nEND_BATCH$/)?.[1] ?? ''; return response(QWEN_RESPONSE, batch); } if (request.model === QWEN) return response(QWEN_RESPONSE, MEANING_EN); return response(GRANITE_RESPONSE, pass()); }; try { const out = await translateSegments(req({ segments: [{ id: 'empty-id', text: '' }, { id: 'filled', text: 'Hello' }] }), CONFIG); assert.equal(out.segments[0]!.text, ''); } finally { globalThis.fetch = old; } });
