import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { CorrectionRoute, ErrorDeltaKind, MeaningEvidenceGraph } from './integrity-control.js';
import type { RiskClass } from './risk-router.js';

export const TRANSLATION_MEMORY_SCHEMA = 'asteria.translation-memory/v1';
export const TRANSLATION_MEMORY_BINDING_VERSION = 'asteria.translation-memory-binding/v1';
const MAX_RECORD_BYTES = 4096, MAX_READ_BYTES = 4 * 1024 * 1024, COMPACT_AT_BYTES = 16 * 1024 * 1024, COMPACT_KEEP_RECORDS = 2048, MAX_MATCHES = 8;
const KINDS = new Set<ErrorDeltaKind>(['omission','unsupported_addition','contradiction','polarity','condition_exception','modality','entity_reference','quantity_time','wrong_language','literal_structure','unresolved_guess','semantic_other']);
const ROUTES = new Set<CorrectionRoute>(['PASS','LOCAL_FIX','FRESH_REGENERATE','REANALYZE','FAIL_CLOSED']);
const RISKS = new Set<RiskClass>(['simple','complex','high-risk','ambiguous']);
type MemoryKind = 'ATTEMPT_REJECTED' | 'RUN_ACCEPTED';

export type TranslationMemoryRecord = { schema: typeof TRANSLATION_MEMORY_SCHEMA; record_id: string; kind: MemoryKind; binding_version: typeof TRANSLATION_MEMORY_BINDING_VERSION; binding_digest: string; evidence_digest: string; profile_version: string; source_language: string | null; target_language: string; risk_class: RiskClass; attempt_no: number; route: CorrectionRoute; failure_kinds: ErrorDeltaKind[]; failure_fingerprint: string | null; created_at: number };
export type FailureHistoryRecord = { record_id: string; attempt_no: number; route: CorrectionRoute; failure_kinds: readonly ErrorDeltaKind[]; failure_fingerprint: string; new_evidence: boolean };
export type FailureHistoryRead = { records: readonly FailureHistoryRecord[]; guidance_records: number; reopened_records: number; guidance: string };
export type TranslationMemoryContext = { bindingDigest: string; evidenceDigest: string; profileVersion: string; sourceLanguage?: string; targetLanguage: string; riskClass: RiskClass };
export interface TranslationMemory { readFailures(context: Pick<TranslationMemoryContext,'bindingDigest'|'evidenceDigest'>): Promise<FailureHistoryRead>; appendFailure(context: TranslationMemoryContext & { attemptNo: number; route: CorrectionRoute; failureKinds: readonly ErrorDeltaKind[] }): Promise<boolean>; appendAccepted(context: TranslationMemoryContext & { attemptNo: number }): Promise<boolean>; }

function stable(value: unknown): string { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; const record=value as Record<string,unknown>; return `{${Object.keys(record).sort().map((key)=>`${JSON.stringify(key)}:${stable(record[key])}`).join(',')}}`; }
function sha256(value: unknown): string { return crypto.createHash('sha256').update(stable(value),'utf8').digest('hex'); }
function hashLike(value: unknown): value is string { return typeof value === 'string' && /^[a-f0-9]{64}$/i.test(value); }
function safeText(value: unknown, max=128): value is string { return typeof value === 'string' && value.length > 0 && value.length <= max && /^[A-Za-z0-9._:-]+$/.test(value); }
export function translationInputBindingDigest(input:{profileVersion:string;sourceLanguage?:string;targetLanguage:string;translatorModel:string;validatorModel:string;originals:readonly string[]}):string { return sha256({binding_version:TRANSLATION_MEMORY_BINDING_VERSION,profile_version:input.profileVersion,source_language:input.sourceLanguage??null,target_language:input.targetLanguage,translator_model:input.translatorModel,validator_model:input.validatorModel,originals:input.originals}); }
export function meaningEvidenceDigest(graph:MeaningEvidenceGraph):string { return sha256(graph); }
function uniqueKinds(kinds:readonly ErrorDeltaKind[]):ErrorDeltaKind[]{ return [...new Set(kinds.filter((kind)=>KINDS.has(kind)))].sort() as ErrorDeltaKind[]; }
function validRecord(value:unknown):value is TranslationMemoryRecord { if(!value||typeof value!=='object'||Array.isArray(value))return false; const r=value as Partial<TranslationMemoryRecord>; return r.schema===TRANSLATION_MEMORY_SCHEMA&&r.binding_version===TRANSLATION_MEMORY_BINDING_VERSION&&(r.kind==='ATTEMPT_REJECTED'||r.kind==='RUN_ACCEPTED')&&hashLike(r.record_id)&&hashLike(r.binding_digest)&&hashLike(r.evidence_digest)&&safeText(r.profile_version,128)&&(r.source_language===null||safeText(r.source_language,64))&&safeText(r.target_language,64)&&RISKS.has(r.risk_class as RiskClass)&&Number.isInteger(r.attempt_no)&&Number(r.attempt_no)>=1&&ROUTES.has(r.route as CorrectionRoute)&&Array.isArray(r.failure_kinds)&&r.failure_kinds.every((kind)=>KINDS.has(kind))&&(r.failure_fingerprint===null||hashLike(r.failure_fingerprint))&&Number.isFinite(r.created_at); }
function recordBytes(record:TranslationMemoryRecord):number{return Buffer.byteLength(JSON.stringify(record),'utf8');}
function failureGuidance(records:readonly FailureHistoryRecord[]):string { const kinds=uniqueKinds(records.filter((r)=>!r.new_evidence).flatMap((r)=>r.failure_kinds)); if(!kinds.length)return ''; return `PERSISTENT_FAILURE_MEMORY: prior attempts with the same input binding and the same accepted source evidence were rejected for semantic error classes: ${kinds.join(', ')}. Do not copy or reconstruct any prior candidate. Translate the ORIGINAL again and avoid repeating these error classes.`; }

export class JsonlTranslationMemory implements TranslationMemory {
  private writeChain:Promise<void>=Promise.resolve();
  constructor(readonly filePath:string){if(!filePath||!path.isAbsolute(filePath))throw new Error('ASTERIA_MEMORY_FILE_ABSOLUTE_REQUIRED');}
  private async readText():Promise<string>{try{const stat=await fs.stat(this.filePath);if(stat.size<=MAX_READ_BYTES)return await fs.readFile(this.filePath,'utf8');const handle=await fs.open(this.filePath,'r');try{const length=Math.min(MAX_READ_BYTES,stat.size),buffer=Buffer.alloc(length);await handle.read(buffer,0,length,stat.size-length);const text=buffer.toString('utf8'),first=text.indexOf('\n');return first>=0?text.slice(first+1):'';}finally{await handle.close();}}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return '';throw error;}}
  private async records():Promise<TranslationMemoryRecord[]>{const text=await this.readText(),out:TranslationMemoryRecord[]=[];for(const line of text.split('\n')){if(!line.trim())continue;try{const parsed:unknown=JSON.parse(line);if(validRecord(parsed))out.push(parsed);}catch{/* untrusted malformed memory is ignored */}}return out;}
  async readFailures(context:Pick<TranslationMemoryContext,'bindingDigest'|'evidenceDigest'>):Promise<FailureHistoryRead>{if(!hashLike(context.bindingDigest)||!hashLike(context.evidenceDigest))throw new Error('ASTERIA_MEMORY_DIGEST_INVALID');await this.writeChain.catch(()=>undefined);const all=await this.records(),found:FailureHistoryRecord[]=[],seen=new Set<string>();for(let i=all.length-1;i>=0&&found.length<MAX_MATCHES;i-=1){const record=all[i]!;if(record.kind!=='ATTEMPT_REJECTED'||record.binding_digest!==context.bindingDigest||!record.failure_fingerprint)continue;if(seen.has(record.failure_fingerprint))continue;seen.add(record.failure_fingerprint);found.push(Object.freeze({record_id:record.record_id,attempt_no:record.attempt_no,route:record.route,failure_kinds:Object.freeze([...record.failure_kinds]),failure_fingerprint:record.failure_fingerprint,new_evidence:record.evidence_digest!==context.evidenceDigest}));}const guidance=failureGuidance(found);return Object.freeze({records:Object.freeze(found),guidance_records:found.filter((r)=>!r.new_evidence).length,reopened_records:found.filter((r)=>r.new_evidence).length,guidance});}
  private async compactIfNeeded():Promise<void>{try{const stat=await fs.stat(this.filePath);if(stat.size<COMPACT_AT_BYTES)return;const all=await this.records(),keep=all.slice(-COMPACT_KEEP_RECORDS),temp=`${this.filePath}.tmp`;await fs.writeFile(temp,keep.map((r)=>JSON.stringify(r)).join('\n')+(keep.length?'\n':''),{encoding:'utf8',mode:0o600});await fs.rename(temp,this.filePath);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}
  private appendRecord(record:TranslationMemoryRecord):Promise<boolean>{let wrote=false;const operation=this.writeChain.catch(()=>undefined).then(async()=>{if(recordBytes(record)>MAX_RECORD_BYTES)throw new Error('ASTERIA_MEMORY_RECORD_TOO_LARGE');await fs.mkdir(path.dirname(this.filePath),{recursive:true,mode:0o700});const existing=await this.records();if(existing.some((item)=>item.record_id===record.record_id))return;await this.compactIfNeeded();await fs.appendFile(this.filePath,`${JSON.stringify(record)}\n`,{encoding:'utf8',mode:0o600,flag:'a'});wrote=true;});this.writeChain=operation.then(()=>undefined);return operation.then(()=>wrote);}
  appendFailure(context:TranslationMemoryContext&{attemptNo:number;route:CorrectionRoute;failureKinds:readonly ErrorDeltaKind[]}):Promise<boolean>{const failureKinds=uniqueKinds(context.failureKinds);if(!failureKinds.length)throw new Error('ASTERIA_MEMORY_FAILURE_KIND_REQUIRED');const failureFingerprint=sha256({route:context.route,failure_kinds:failureKinds}),identity={kind:'ATTEMPT_REJECTED',binding_digest:context.bindingDigest,evidence_digest:context.evidenceDigest,attempt_no:context.attemptNo,failure_fingerprint:failureFingerprint};return this.appendRecord({schema:TRANSLATION_MEMORY_SCHEMA,record_id:sha256(identity),kind:'ATTEMPT_REJECTED',binding_version:TRANSLATION_MEMORY_BINDING_VERSION,binding_digest:context.bindingDigest,evidence_digest:context.evidenceDigest,profile_version:context.profileVersion,source_language:context.sourceLanguage??null,target_language:context.targetLanguage,risk_class:context.riskClass,attempt_no:context.attemptNo,route:context.route,failure_kinds:failureKinds,failure_fingerprint:failureFingerprint,created_at:Date.now()});}
  appendAccepted(context:TranslationMemoryContext&{attemptNo:number}):Promise<boolean>{const identity={kind:'RUN_ACCEPTED',binding_digest:context.bindingDigest,evidence_digest:context.evidenceDigest,attempt_no:context.attemptNo};return this.appendRecord({schema:TRANSLATION_MEMORY_SCHEMA,record_id:sha256(identity),kind:'RUN_ACCEPTED',binding_version:TRANSLATION_MEMORY_BINDING_VERSION,binding_digest:context.bindingDigest,evidence_digest:context.evidenceDigest,profile_version:context.profileVersion,source_language:context.sourceLanguage??null,target_language:context.targetLanguage,risk_class:context.riskClass,attempt_no:context.attemptNo,route:'PASS',failure_kinds:[],failure_fingerprint:null,created_at:Date.now()});}
}
